
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './Components/providers'
import NavComponent from './Components/Navbar'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
      <Providers>
      <NavComponent/> 
      {children}
      </Providers>
    
      </body>
    </html>
  )
}
